// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['/app/src/element.js'], function(Element) {
    var Box;
    Box = (function(_super) {

      __extends(Box, _super);

      function Box() {
        return Box.__super__.constructor.apply(this, arguments);
      }

      return Box;

    })(Element);
    return Box;
  });

}).call(this);
