// Generated by CoffeeScript 1.4.0
(function() {

  define(['/app/src/connector.js', '/app/src/packets.js'], function(Connector, Packets) {
    return describe('connector', function() {
      beforeEach(function() {
        this.scene = {};
        this.connector = new Connector(this.scene);
        return this.connector.ws = {
          send: function() {
            return true;
          }
        };
      });
      return it('should encode valid msgpack', function() {
        var buf;
        this.connector.sendPacket([0x01, "<xml something />"]);
        spyOn(this.connector.ws, 'send');
        this.connector.dispatchPackets();
        buf = this.connector.ws.send.mostRecentCall.args[0];
        return expect(buf.byteLength).toEqual(21);
      });
    });
  });

}).call(this);
