// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    urlArgs: "nonce=" + (new Date()).getTime()
  });

  define(["/app/components/jasmine/lib/jasmine-core/jasmine.js", "/app/components/jasmine/lib/jasmine-core/jasmine-html.js", "/app/components/jquery/dist/jquery.js", "/app/components/threejs/build/three.js", "./uploader_spec.js"], function() {
    var jasmineEnv, trivialReporter;
    jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;
    trivialReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(trivialReporter);
    jasmineEnv.specFilter = function(spec) {
      return trivialReporter.specFilter(spec);
    };
    return jasmineEnv.execute();
  });

}).call(this);
