// Generated by CoffeeScript 1.4.0
(function() {

  define(['/app/src/uploader.js'], function(Uploader) {
    return describe('uploader', function() {
      beforeEach(function() {
        this.client = {
          connector: {}
        };
        this.uploader = new Uploader(this.client);
        return this.uploader.position = new THREE.Vector3(1, 2, 3);
      });
      return it('should create a packet on success', function() {
        spyOn(this.client.connector, 'sendPackets');
        this.uploader.onSuccess('//asset-server/models/123.js');
        return expect(this.client.connector.sendPackets).toHaveBeenCalled();
      });
    });
  });

}).call(this);
