// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Authenticator;

    Authenticator = (function() {
      function Authenticator() {}

      Authenticator.prototype.auth = function() {};

      return Authenticator;

    })();
    return Authenticator;
  });

}).call(this);
