// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Authenticator;

    Authenticator = (function() {
      function Authenticator() {}

      Authenticator.prototype.auth = function() {
        var div, ifame;

        div = $("<div id='authenticator' />");
        ifame = $("<iframe src='");
        return div.addClass('a');
      };

      return Authenticator;

    })();
    return Authenticator;
  });

}).call(this);
