// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(["/app/components/msgpack-js-browser/msgpack.js", "/app/src/packets.js"], function(msgpack_, Packets) {
    var Connector;

    Connector = (function() {
      function Connector(scene, camera, host, port) {
        this.scene = scene;
        this.camera = camera;
        this.onMessage = __bind(this.onMessage, this);
        this.host = host || window.location.host.split(":")[0];
        this.port = port || 8080;
        this.protocol = "mv-protocol";
        this.packets = [];
      }

      Connector.prototype.connect = function() {
        var _this = this;

        this.ws = new WebSocket("ws://" + this.host + ":" + this.port + "/", this.protocol);
        this.ws.binaryType = 'arraybuffer';
        this.ws.onopen = function() {
          console.log("Opened socket");
          return _this.interval = setInterval(_this.tick, 1000 / 2);
        };
        this.ws.onclose = function() {
          console.log("Closed socket");
          return clearInterval(_this.interval);
        };
        return this.ws.onmessage = this.onMessage;
      };

      Connector.prototype.sendPacket = function(packet) {
        return this.packets.push(packet);
      };

      Connector.prototype.dispatchPackets = function() {
        return this.ws.send(msgpack.encode(this.packets));
      };

      Connector.prototype.tick = function() {};

      Connector.prototype.onMessage = function(e) {
        var klass, message, messages, packet, packetId, _i, _len;

        messages = msgpack.decode(e.data);
        for (_i = 0, _len = messages.length; _i < _len; _i++) {
          message = messages[_i];
          packetId = message[0];
          klass = Packets.dictionary[packetId];
          packet = new klass(message);
          packet.process(this.scene);
        }
        if (this.packets.length > 0) {
          this.dispatchPackets();
        }
        return this.packets = [];
      };

      return Connector;

    })();
    return Connector;
  });

}).call(this);
