// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var Element;
    Element = (function() {

      function Element(id) {
        this.id = id;
        this.position = null;
        this.rotation = null;
        this.scale = null;
      }

      Element.prototype.notify = function() {};

      return Element;

    })();
    return Element;
  });

}).call(this);
