// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var Element;
    Element = (function() {

      function Element(id) {
        this.id = id;
        this.position = new THREE.Vector3(0, 0, 0);
        this.rotation = new THREE.Euler(0, 0, 0);
        this.scale = new THREE.Vector3(0, 0, 0);
      }

      Element.prototype.getInnerXML = function() {
        var child, el;
        el = $("<xml><" + this.nodeName + " /></xml>");
        child = el.children();
        child.attr('position', [this.position.x, this.position.y, this.position.z].join(" "));
        child.attr('rotation', [this.rotation.x, this.rotation.y, this.rotation.z].join(" "));
        child.attr('scale', [this.scale.x, this.scale.y, this.scale.z].join(" "));
        if (this.src) {
          child.attr('src', this.src);
        }
        return el.html();
      };

      Element.prototype.notify = function() {};

      return Element;

    })();
    return Element;
  });

}).call(this);
