// Generated by CoffeeScript 1.4.0
(function() {

  define(['/app/components/threejs/build/three.js', '/app/components/tweenjs/build/tween.min.js', '/app/src/utils.js', '/app/src/elements/box.js'], function(THREE_, TWEEN_, utils, Box) {
    var PacketGone, PacketIntroducing, PacketUpdate, dictionary, key, packets, value;
    PacketIntroducing = (function() {

      PacketIntroducing.id = 0x01;

      function PacketIntroducing(array) {
        var nil;
        nil = array[0], this.xml = array[1];
      }

      PacketIntroducing.prototype.process = function(scene) {
        var dom, element;
        element = scene.getElementById(this.id);
        if (element) {
          scene.removeChild(element);
        }
        dom = $(this.xml).first();
        this.id = dom.attr('id');
        element = (function() {
          switch (dom.get(0).nodeName) {
            case 'BOX':
              return new Box(this.id);
            default:
              throw "Invalid element introduced";
          }
        }).call(this);
        element.position = utils.attributeToVector(dom.attr('position'));
        element.rotation = utils.attributeToEuler(dom.attr('rotation'));
        element.scale = utils.attributeToVector(dom.attr('scale'));
        scene.appendChild(element);
        return true;
      };

      return PacketIntroducing;

    })();
    PacketUpdate = (function() {

      PacketUpdate.id = 0x02;

      function PacketUpdate(array) {
        var nil;
        nil = array[0], this.id = array[1], this.positionX = array[2], this.positionY = array[3], this.positionZ = array[4], this.rotationX = array[5], this.rotationY = array[6], this.rotationZ = array[7];
      }

      PacketUpdate.prototype._byteToEuler = function(byte) {
        return byte / 256.0 * 2 * Math.PI;
      };

      PacketUpdate.prototype.process = function(scene) {
        var element, tween;
        element = scene.getElementById(this.id);
        if (!element) {
          return;
        }
        tween = new TWEEN.Tween({
          x: element.position.x,
          y: element.position.y,
          z: element.position.z
        });
        tween.to({
          x: this.positionX,
          y: this.positionY,
          z: this.positionZ
        }, 500).easing(TWEEN.Easing.Linear.None).onUpdate(function() {
          return element.position = new THREE.Vector3(this.x, this.y, this.z);
        }).start();
        element.rotation = new THREE.Euler(this._byteToEuler(this.rotationX, this.rotationY, this.rotationZ));
        element.notify();
        return true;
      };

      return PacketUpdate;

    })();
    PacketGone = (function() {

      PacketGone.id = 0x03;

      function PacketGone(array) {
        var nil;
        nil = array[0], this.id = array[1];
      }

      PacketGone.prototype.process = function(scene) {
        var element;
        element = scene.getElementById(this.id);
        if (!element) {
          scene.removeChild(element);
        }
        return true;
      };

      return PacketGone;

    })();
    packets = {
      "Introducing": PacketIntroducing,
      "Update": PacketUpdate,
      "Gone": PacketGone
    };
    dictionary = {};
    for (key in packets) {
      value = packets[key];
      dictionary[value.id] = value;
    }
    return {
      packets: packets,
      dictionary: dictionary
    };
  });

}).call(this);
