// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var utils;
    utils = {
      attributeToVector: function(attributeString) {
        var x, y, z, _ref;
        _ref = attributeString.split(' ').map(parseFloat), x = _ref[0], y = _ref[1], z = _ref[2];
        return new THREE.Vector3(x, y, z);
      },
      attributeToEuler: function(attributeString) {
        var x, y, z, _ref;
        _ref = attributeString.split(' ').map(parseFloat), x = _ref[0], y = _ref[1], z = _ref[2];
        return new THREE.Euler(x, y, z);
      }
    };
    return utils;
  });

}).call(this);
